In [35]:
import pandas as pd
import numpy as np
import math

In [9]:
#1. Створіть одновимірний масив (вектор) з числами, які є кубами натуральних чисел, починаючи з 1, та виведіть його значення.

cubes = np.array([n**3 for n in range(1, 11)])
print(cubes)

[   1    8   27   64  125  216  343  512  729 1000]


In [8]:
#2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями факторіалів перших натуральних чисел.

factorials = np.array([[math.factorial(i) for i in range(1, 10)]]).reshape(3, 3)
print(factorials)

[[     1      2      6]
 [    24    120    720]
 [  5040  40320 362880]]


In [24]:
#3. Створіть масив розміром 3x3, заповніть його випадковими цілими числами від -5 до 5 та знайдіть суму модулів кожного рядка

random_matrix = np.random.randint(-5, 6, (3, 3))
sum_of_abs_rows = np.sum(np.abs(random_matrix), axis=1)

print("Масив:\n", random_matrix)
print("Сума модулів кожного рядка:", sum_of_abs_rows)

Масив:
 [[ 2  1  5]
 [ 0  3  4]
 [ 4 -3 -4]]
Сума модулів кожного рядка: [ 8  7 11]


In [23]:
#4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть середнє геометричне всіх елементів.

random_matrix = np.random.rand(3, 3)
geometric_mean = np.prod(random_matrix)**(1/random_matrix.size)

print("Масив:\n", random_matrix)
print("Середнє геометричне всіх елементів:", geometric_mean)

Масив:
 [[0.38937654 0.23561953 0.90702792]
 [0.35884304 0.4637925  0.28450736]
 [0.78384103 0.96655301 0.27698214]]
Середнє геометричне всіх елементів: 0.4544562726956304


In [22]:
#5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими дійсними числами від 0 до 1 та виконайте на них поелементні операції додавання, віднімання та множення

array1 = np.random.rand(5)
array2 = np.random.rand(5)
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Перший масив:", array1)
print("Другий масив:", array2)
print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)

Перший масив: [0.6148093  0.10864292 0.6286218  0.37554949 0.28668123]
Другий масив: [0.70674011 0.08833315 0.28580849 0.96364103 0.55093738]
Додавання: [1.32154941 0.19697607 0.91443029 1.33919052 0.83761861]
Віднімання: [-0.09193081  0.02030977  0.34281332 -0.58809155 -0.26425615]
Множення: [0.43451039 0.00959677 0.17966544 0.3618949  0.15794341]


In [21]:
#6. Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 5 та знайдіть їх добуток

matrix1 = np.random.randint(1, 6, (3, 3))
matrix2 = np.random.randint(1, 6, (3, 3))
product = np.dot(matrix1, matrix2)

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)
print("Добуток матриць:\n", product)

Перша матриця:
 [[3 3 1]
 [2 5 5]
 [5 4 2]]
Друга матриця:
 [[5 4 1]
 [3 1 5]
 [5 1 4]]
Добуток матриць:
 [[29 16 22]
 [50 18 47]
 [47 26 33]]


In [20]:
#7. Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою

matrix1 = np.random.randint(1, 6, (2, 3))
matrix2 = np.random.randint(1, 6, (3, 2))
product = np.dot(matrix1, matrix2)

print("Перша матриця (2x3):\n", matrix1)
print("Друга матриця (3x2):\n", matrix2)
print("Добуток матриць (2x2):\n", product)

Перша матриця (2x3):
 [[5 5 5]
 [1 2 3]]
Друга матриця (3x2):
 [[2 5]
 [1 1]
 [3 3]]
Добуток матриць (2x2):
 [[30 45]
 [13 16]]


In [26]:
#8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.

matrix = np.random.randint(1, 16, (3, 3))
inverse_matrix = np.linalg.inv(matrix)

print("Матриця (3x3):\n", matrix)
print("Обернена матриця (3x3):\n", inverse_matrix)

Матриця (3x3):
 [[ 9 12  7]
 [ 3  9 14]
 [15  1 10]]
Обернена матриця (3x3):
 [[ 0.03958333 -0.05885417  0.0546875 ]
 [ 0.09375    -0.0078125  -0.0546875 ]
 [-0.06875     0.0890625   0.0234375 ]]


In [27]:
#9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 10 та транспонуйте її.

matrix = np.random.rand(4, 4) * 10
transposed_matrix = np.transpose(matrix)

print("Оригінальна матриця (4x4):\n", matrix)
print("Транспонована матриця (4x4):\n", transposed_matrix)

Оригінальна матриця (4x4):
 [[7.28416289 6.86453844 1.03161333 2.07385788]
 [6.15512128 0.28564055 4.08525117 5.11780619]
 [4.05046548 6.4688762  7.2034015  2.38500841]
 [1.45989319 4.16609024 4.92187765 7.59076577]]
Транспонована матриця (4x4):
 [[7.28416289 6.15512128 4.05046548 1.45989319]
 [6.86453844 0.28564055 6.4688762  4.16609024]
 [1.03161333 4.08525117 7.2034015  4.92187765]
 [2.07385788 5.11780619 2.38500841 7.59076577]]


In [28]:
#10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

matrix = np.random.rand(3, 4)
vector = np.random.rand(4, 1)
product = np.dot(matrix, vector)

print("Матриця (3x4):\n", matrix)
print("Вектор (4x1):\n", vector)
print("Добуток матриці на вектор (3x1):\n", product)

Матриця (3x4):
 [[0.65967907 0.33729707 0.0199402  0.01047094]
 [0.63723717 0.18418302 0.68744494 0.4299703 ]
 [0.19906358 0.93223888 0.67818491 0.38879313]]
Вектор (4x1):
 [[0.93060653]
 [0.33543633]
 [0.29098529]
 [0.59649247]]
Добуток матриці на вектор (3x1):
 [[0.73909149]
 [1.11130916]
 [0.92721067]]


In [29]:
#11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор

matrix = np.random.rand(2, 3)
vector = np.random.rand(3, 1)
result = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця:
[[0.33299378 0.29298869 0.26744738]
 [0.17331927 0.35899277 0.05407028]]

Вектор:
[[0.41282495]
 [0.62085905]
 [0.85668323]]

Добуток матриці на вектор:
[[0.5484905 ]
 [0.34075553]]


In [30]:
#12. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму елементів діагоналі обох матриць (окремо).

matrix1 = np.random.randint(1, 11, size=(3, 3))
matrix2 = np.random.randint(1, 11, size=(3, 3))

sum_diag_matrix1 = np.trace(matrix1)
sum_diag_matrix2 = np.trace(matrix2)

print("Матриця 1:")
print(matrix1)
print("Сума діагоналі Матриці 1:", sum_diag_matrix1)
print("\nМатриця 2:")
print(matrix2)
print("Сума діагоналі Матриці 2:", sum_diag_matrix2)

Матриця 1:
[[2 4 8]
 [1 4 5]
 [5 9 6]]
Сума діагоналі Матриці 1: 12

Матриця 2:
[[ 6  5 10]
 [ 4  4 10]
 [ 6  3  3]]
Сума діагоналі Матриці 2: 13


In [31]:
#13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть добуток їх елементів

matrix1 = np.random.randint(-5, 6, size=(2, 2))
matrix2 = np.random.randint(-5, 6, size=(2, 2))
product_matrix1 = np.prod(matrix1)
product_matrix2 = np.prod(matrix2)

print("Матриця 1:")
print(matrix1)
print("Добуток елементів Матриці 1:", product_matrix1)
print("\nМатриця 2:")
print(matrix2)
print("Добуток елементів Матриці 2:", product_matrix2)

Матриця 1:
[[-5 -1]
 [-4  2]]
Добуток елементів Матриці 1: -40

Матриця 2:
[[-5  3]
 [ 1 -4]]
Добуток елементів Матриці 2: 60


In [33]:
#14. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть найбільший елемент матриці.

matrix = np.random.randint(1, 11, size=(3, 3))
max_element = np.max(matrix)

print("Матриця:")
print(matrix)
print("Найбільший елемент матриці:", max_element)

Матриця:
[[10  6  5]
 [ 1  2  6]
 [ 8  4  2]]
Найбільший елемент матриці: 10


In [34]:
#15. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить кількість від'ємних елементів в кожному рядку матриці.

matrix = np.random.uniform(-1, 1, (4, 4))
negative_counts = np.sum(matrix < 0, axis=1).reshape(4, 1)

print("Матриця:")
print(matrix)
print("\nВектор-стовпчик з кількістю від'ємних елементів в кожному рядку:")
print(negative_counts)

Матриця:
[[ 0.89985301 -0.97136939  0.96070187  0.21768315]
 [ 0.65863574  0.43112903 -0.22126177  0.87668919]
 [-0.35969177 -0.59367373  0.61034587  0.76851737]
 [ 0.89137603  0.75180352 -0.65117265  0.63955164]]

Вектор-стовпчик з кількістю від'ємних елементів в кожному рядку:
[[1]
 [1]
 [2]
 [1]]


In [ ]:
# У ході виконання лабораторної роботи ми ознайомилися з основними операціями над матрицями в Python за допомогою бібліотеки NumPy. Ми навчилися створювати матриці різних розмірів і типів, заповнювати їх випадковими числами, виконувати різні арифметичні операції, такі як множення матриць, знаходження добутку елементів, суми діагональних елементів, та обчислення кількості від'ємних значень у матриці.